# Generated by Django 5.1 on 2024-08-22 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ягоды')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Декор')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Количество уровней')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Форма')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Топпинг')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='account.event', verbose_name='Повод')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('price', models.FloatField(verbose_name='Цена')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('address', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('customer_name', models.TextField(blank=True, default='', verbose_name='Имя')),
                ('phone_number', models.TextField(blank=True, default='', verbose_name='Номер телефона')),
                ('email', models.TextField(blank=True, default='', verbose_name='Почта')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('CatalogueCake', 'CustomCake')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordrs', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.orderstatus', verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('title', models.TextField(blank=True, default='', verbose_name='Надпись')),
                ('berry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='account.berry', verbose_name='Ягоды')),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='account.decoration', verbose_name='Декор')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='account.level', verbose_name='Количество уровней')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='account.shape', verbose_name='Форма')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='account.topping', verbose_name='Топпинг')),
            ],
        ),
    ]
