# Generated by Django 5.1 on 2024-08-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_berry_decoration_event_level_orderstatus_shape_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berry',
            options={'verbose_name': 'Ягоды', 'verbose_name_plural': 'Ягоды'},
        ),
        migrations.AlterModelOptions(
            name='cataloguecake',
            options={'verbose_name': 'Готовый торт', 'verbose_name_plural': 'Готовые торты'},
        ),
        migrations.AlterModelOptions(
            name='customcake',
            options={'verbose_name': 'Кастомный торт', 'verbose_name_plural': 'Кастомные торты'},
        ),
        migrations.AlterModelOptions(
            name='decoration',
            options={'verbose_name': 'Декор', 'verbose_name_plural': 'Декор'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Повод', 'verbose_name_plural': 'Поводы'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Количество уровней', 'verbose_name_plural': 'Количество уровней'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказа'},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'verbose_name': 'Форма', 'verbose_name_plural': 'Формы'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': 'Топпинг', 'verbose_name_plural': 'Топпинги'},
        ),
        migrations.AlterField(
            model_name='order',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['content_type', 'object_id'], name='account_ord_content_27e30e_idx'),
        ),
    ]
