# Generated by Django 5.1 on 2024-08-23 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_berry_options_alter_cataloguecake_options_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ("cataloguecake", "customcake")},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Тип торта",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="object_id",
            field=models.PositiveIntegerField(verbose_name="ID торта"),
        ),
    ]
