# Generated by Django 5.1 on 2024-08-23 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Berry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Ягоды")),
                ("price", models.FloatField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Ягоды",
                "verbose_name_plural": "Ягоды",
            },
        ),
        migrations.CreateModel(
            name="Decoration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Декор")),
                ("price", models.FloatField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Декор",
                "verbose_name_plural": "Декор",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название")),
            ],
            options={
                "verbose_name": "Повод",
                "verbose_name_plural": "Поводы",
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Количество уровней")),
                ("price", models.FloatField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Количество уровней",
                "verbose_name_plural": "Количество уровней",
            },
        ),
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Форма")),
                ("price", models.FloatField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Форма",
                "verbose_name_plural": "Формы",
            },
        ),
        migrations.CreateModel(
            name="Topping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Топпинг")),
                ("price", models.FloatField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Топпинг",
                "verbose_name_plural": "Топпинги",
            },
        ),
        migrations.CreateModel(
            name="CatalogueCake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название")),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cakes",
                        to="cakes.event",
                        verbose_name="Повод",
                    ),
                ),
            ],
            options={
                "verbose_name": "Готовый торт",
                "verbose_name_plural": "Готовые торты",
            },
        ),
        migrations.CreateModel(
            name="CustomCake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "title",
                    models.TextField(blank=True, default="", verbose_name="Надпись"),
                ),
                (
                    "berry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cakes",
                        to="cakes.berry",
                        verbose_name="Ягоды",
                    ),
                ),
                (
                    "decoration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cakes",
                        to="cakes.decoration",
                        verbose_name="Декор",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cakes",
                        to="cakes.level",
                        verbose_name="Количество уровней",
                    ),
                ),
                (
                    "shape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cakes",
                        to="cakes.shape",
                        verbose_name="Форма",
                    ),
                ),
                (
                    "topping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cakes",
                        to="cakes.topping",
                        verbose_name="Топпинг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кастомный торт",
                "verbose_name_plural": "Кастомные торты",
            },
        ),
    ]
