# Generated by Django 5.1 on 2024-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0003_cataloguecake_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cataloguecake",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/img",
                verbose_name="Изображение",
            ),
        ),
    ]
