# Generated by Django 5.1 on 2024-08-23 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название")),
            ],
            options={
                "verbose_name": "Статус заказа",
                "verbose_name_plural": "Статусы заказа",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="ID торта")),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий"
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий"
                    ),
                ),
                (
                    "customer_name",
                    models.TextField(blank=True, default="", verbose_name="Имя"),
                ),
                (
                    "phone_number",
                    models.TextField(
                        blank=True, default="", verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.TextField(blank=True, default="", verbose_name="Почта"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Изменено"
                    ),
                ),
                (
                    "date_delivered",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Доставлено"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("cataloguecake", "customcake")},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_contenttype",
                        to="contenttypes.contenttype",
                        verbose_name="Тип торта",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orders.orderstatus",
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="orders_orde_content_052ba7_idx",
                    )
                ],
            },
        ),
    ]
