# Generated by Django 5.1 on 2024-08-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Неоплачен"),
                    ("PAY", "Оплачен"),
                    ("ACC", "Принят"),
                    ("PREP", "Готовится"),
                    ("OUT", "Передан в доставку"),
                    ("COMP", "Выполнен"),
                    ("CANC", "Отменен"),
                ],
                default="NEW",
                max_length=4,
            ),
        ),
        migrations.DeleteModel(
            name="OrderStatus",
        ),
    ]
