# Generated by Django 5.1 on 2024-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_address_alter_order_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="id платежа"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Адрес"
            ),
        ),
    ]
